# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-08 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.BigIntegerField(null=True, verbose_name='Amount Paid')),
                ('transaction_date', models.DateTimeField(null=True, verbose_name='Date of Transaction')),
                ('payee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payee_user', to=settings.AUTH_USER_MODEL)),
                ('paying_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paying_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
